# Generated by Django 3.0.3 on 2020-09-02 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipa_na_mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnmonlinetransaction',
            name='Amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lnmonlinetransaction',
            name='CheckoutRequestID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lnmonlinetransaction',
            name='MerchantRequestID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lnmonlinetransaction',
            name='MpesaReceiptNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lnmonlinetransaction',
            name='PhoneNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lnmonlinetransaction',
            name='ResultCode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lnmonlinetransaction',
            name='ResultDesc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lnmonlinetransaction',
            name='TransactionDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
