# Generated by Django 3.0.3 on 2020-09-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipa_na_mpesa', '0002_auto_20200902_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnmonlinetransaction',
            name='TransactionDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
