# Generated by Django 3.0.3 on 2020-09-02 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lipa_na_mpesa', '0003_auto_20200902_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnmonlinetransaction',
            name='TransactionDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
